<?php

namespace Cosmiccigarette\Bundle\NSAQueryCreatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * queriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class queriesRepository extends EntityRepository
{
}
